### ISSUE TITLE
You really should mention your source inspiration

### ISSUE THREAD

**Issue by JounQin** [himself65/npm-download-stat#10]
https://npm-stat.com

I'm one of your big fans, so I hope you can do better.

**Comment by uncenter** [comment]
I don't think making charts for download statistics is anything npm-stat.com came up with - this is clearly a very different way of presenting the data, the card with install commands and other details...

**Comment by JounQin** [comment]
> I don't think making charts for download statistics is anything npm-stat.com came up with - this is clearly a very different way of presenting the data, the card with install commands and other details...

But clearly it's the source inspiration.

I'm not talking about the features.

**Comment by uncenter** [comment]
Is it? I'm confused why you think fetching downloads from the NPM API and turning the data into a chart is something reserved for that website and that this project *has* to be based on it. I can't speak for the author but either way this seems silly.

**Comment by JounQin** [comment]
@uncenter Sorry, I'm not talking about charts or any other features. 🥹

I mean the author should mention his source inspiration in readme and tweet.

**Comment by JounQin** [comment]
Sorry for your confusion here.

**Comment by himself65** [comment]
This is inspired by https://francoisbest.com/posts/2023/npm-download-stats-are-down.

And I indeed add the the author to the footer.

**Comment by JounQin** [comment]
Ah, sorry I got wrong with your source inspiration.

But I can't see any related references, can you point it out?

And when ask about this on Twitter, you said

> Npm stat cannot count by version. That’s why

I don't know whether the `Npm stat` is the same thing between us. 😅

**Comment by JounQin** [comment]
@himself65 Thanks for taking my advice. Big fan here.
