### ISSUE TITLE
if the package has no repo 404 is returned

### ISSUE THREAD

**Issue by rawnly** [himself65/npm-download-stat#11]
https://github.com/himself65/npm-download-stat/blob/2597a0989b27d51a907ac2b0faa5273f31f786e0/src/app/%5Bpkg%5D/page.tsx#L71

if the package has no repo (eg: https://npm-stat.link/next-wayfinder) returns 404 [even tho the package exists](https://www.npmjs.com/package/next-wayfinder)

**Comment by himself65** [comment]
Thanks for the ticket
