### ISSUE TITLE
Show package managers commands all directly without personal preference

### ISSUE THREAD

**Issue by JounQin** [himself65/npm-download-stat#18]
I'd raise a PR if you agree.

**Comment by himself65** [comment]
You can implement a feature that allows you to select the preference by clicking down-arrow, then clicking which command and keeping the settings in local storage. That might be better

**Comment by JounQin** [comment]
For the first time, we show no preference, after the user select his/her own preference, we store it in `localStorage`, right?

**Comment by himself65** [comment]
> For the first time, we show no preference, after the user select his/her own preference, we store it in `localStorage`, right?

Yeah, this is a nice feature if people wanna screenshot with their own preferences.

Also talking about the preferences, it might good to have select color, widget size... Just my idea

**Comment by himself65** [comment]
It will be something like https://carbon.now.sh/

**Comment by JounQin** [comment]
> Also talking about the preferences, it might good to have select color, widget size... Just my idea

Haha, it's too big for my brain, I'll implement the basic functionality first.
