### ISSUE TITLE
Search button loading spinner/disabled on form submission 

### ISSUE THREAD

**Issue by T1LT** [himself65/npm-download-stat#20]
Would love to see a loading spinner to indicate the pending status of the form submission. 
Planning on implementing this with the useFormStatus hook from react-dom - [source](https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations#pending-states)
Can open a PR if you want me to.

**Comment by himself65** [comment]
nice to have, I haven't tried that

**Comment by T1LT** [comment]
perfect, will create a PR in a bit!

**Comment by himself65** [comment]
We can use existing component from

```
import { PiSpinnerGapBold } from "react-icons/pi";
```

**Comment by T1LT** [comment]
ooh got it, will do
