### ISSUE TITLE
Firefox: ClipboardItem is not defined

### ISSUE THREAD

**Issue by 5e** [himself65/npm-download-stat#24]
Firefox doesn't support ClipboardItem

**Comment by himself65** [comment]
Thanks for the bug report

**Comment by himself65** [comment]
I will use this https://www.npmjs.com/package/clipboard-polyfill

**Comment by 5e** [comment]
> I will use this https://www.npmjs.com/package/clipboard-polyfill

I see, I have sent a pull request which downloads images instead of copying them, but feel free to do however you find suitable
