### ISSUE TITLE
Download stats stagnant

### ISSUE THREAD

**Issue by adamlui** [himself65/npm-download-stat#29]
I noticed the stats don't match what shields.io generate.

For example, for @adamlui/scsss-to-css, shields.io's https://img.shields.io/npm/d18m/@adamlui/scss-to-css.svg shows:

![image](https://github.com/himself65/npm-download-stat/assets/10906554/a02b28bd-606a-4f84-a4e5-fc5793689169)

...while npm-stat.link's shows https://npm-stat.link/%40adamlui%2Fscss-to-css:

![image](https://github.com/himself65/npm-download-stat/assets/10906554/7a94aaaf-2810-40b4-bf25-1e7d3115c627)

I first visited the npm-stat.link 39 hours ago. Do you know how often it's supposed to update? (shields.io's is at least once a day, but they recently switched from showing All-Time to Last 18 Months so are unusable to me)

Thanks

**Comment by himself65** [comment]
revalidate will be `1h`

https://github.com/himself65/npm-download-stat/blob/84ecf2529bc10c153f31019ad43d2be85ecba2ae/src/lib/fetch-github.ts#L81

**Comment by adamlui** [comment]
@himself65 but I just checked and it's still the old stat 1.8K going on 58h now. Is npm-stat.link supposed to update the image at some point? (I set up a GitHub Action to send daily curl to parse svg from npm-stat.link for downloads stat to auto-update a README badge)

**Comment by adamlui** [comment]
The Action just ran seconds ago, it parsed an updated stat (1.9K)!

![Screenshot_20240327-173842](https://github.com/himself65/npm-download-stat/assets/10906554/cfff7518-cb84-4ec8-a56d-60cbae718916)

Do you know why npm-stat.link is still serving the old image? Also are you saying, the image is supposed to update every hour?

**Comment by adamlui** [comment]
I shift-refreshed + opened in Incognito from desktop and browser and still old (1.8K) stat, I don't think it's a client-side caching issue

**Comment by himself65** [comment]
Ok I see, it's 24h

https://github.com/himself65/npm-download-stat/blob/8fd51306694e6a8290a9fa61f5e917b2ace508b4/src/lib/fetch-npm.ts#L111-L116

**Comment by adamlui** [comment]
but do you know why your site is showing the old SVG in browser view, but curl request succeeds in fetching updated SVG data?

**Comment by himself65** [comment]
what svg

**Comment by adamlui** [comment]
I meant the HTML served at https://npm-stat.link/package

**Comment by adamlui** [comment]
Are you mad?

**Comment by adamlui** [comment]
Also did you copy most the code from Francois is why you didn't even know about basic update frequency

**Comment by adamlui** [comment]
(because the cards look almost identical to his)

**Comment by himself65** [comment]
Sorry, I still don't understand what you are discussing; you could polish your English using GPT.

If you are talking about why data is old, this is because of caching logic by Next.js https://nextjs.org/docs/app/building-your-application/caching because I thought no one would like to see accurate and latest download count. But indeed, it was too outdated, so I changed it to 1 hour for the recent date

**Comment by adamlui** [comment]
Uhh English is my native language, I am saying the HTML you serve for the cards was outdated for 50+ hours, but curl request fetched updated data so something was wrong and I was helping you by reporting it.

> I thought no one would like to see accurate and latest download count. 

That is quite a strange assumption to make, that people don't like things to be accurate

> But indeed, it was too outdated, so I changed it to 1 hour for the recent date

That's overkill just make it 24h, but what is this "for the recent date" meaning

**Comment by adamlui** [comment]
It's still not working, yesterday curl fetched 2K for https://npm-stat.link/%40adamlui%2Fscss-to-css 

![image](https://github.com/himself65/npm-download-stat/assets/10906554/1c4dbf50-ab64-4901-bca6-4c39c06daf3c)

Source: https://github.com/adamlui/js-utils/actions/runs/8475374186/job/23223372040

but 1h ago it fetched 1.9K!

![image](https://github.com/himself65/npm-download-stat/assets/10906554/e50d5c77-f1f9-481e-873e-848ac8d99030)

Source: https://github.com/adamlui/js-utils/actions/runs/8460466649/job/23178707689

This is the workflow routine w/ `curl` https://github.com/adamlui/js-utils/actions/runs/8460466649/workflow#L61-L70

The bug caused my total downloads shield that uses these curl stats to drop (which is mathematically impossible)

![image](https://github.com/himself65/npm-download-stat/assets/10906554/2dac978c-3818-4fd6-8a49-2695baa4faec)
